const markerImages = {
  "alameda": require('../../assets/images/alameda/i1.webp'),
  "allendeRamon": require('../../assets/images/allendeRamon/i1.webp'),
  "ancira": require('../../assets/images/ancira/i1.webp'),
  "arco": require('../../assets/images/arco/i1.webp'),
  "bautista": require('../../assets/images/bautista/i1.webp'),
  "bguadalupe": require('../../assets/images/bguadalupe/i1.webp'),
  "botica": require('../../assets/images/botica/i1.webp'),
  "boticaroble": require('../../assets/images/boticaroble/i1.webp'),
  "broble": require('../../assets/images/broble/i1.webp'),
  "calleReal": require('../../assets/images/calleReal/i1.webp'),
  "calleTeatroConsti": require('../../assets/images/calleTeatroConsti/i1.webp'),
  "capLourdes": require('../../assets/images/capLourdes/i1.webp'),
  "capuchinas": require('../../assets/images/capuchinas/i1.webp'),
  "casabanos": require('../../assets/images/casabanos/i1.webp'),
  "catedral-mty": require('../../assets/images/catedral-mty/i1.webp'),
  "ccivil": require('../../assets/images/ccivil/i1.webp'),
  "ccosmos": require('../../assets/images/ccosmos/i1.webp'),
  "cine-elizondo": require('../../assets/images/cine-elizondo/i1.webp'),
  "circulo-mercantil": require('../../assets/images/circulo-mercantil/i1.webp'),
  "ciudadela": require('../../assets/images/ciudadela/i1.webp'),
  "comerciantesRio": require('../../assets/images/comerciantesRio/i1.webp'),
  "croble": require('../../assets/images/croble/i1.webp'),
  "cSA": require('../../assets/images/cSA/i1.webp'),
  "cwash": require('../../assets/images/cwash/i1.webp'),
  "edamas": require('../../assets/images/edamas/i1.webp'),
  "escuelaNormal": require('../../assets/images/escuelaNormal/i1.webp'),
  "ferro": require('../../assets/images/ferro/i1.webp'),
  "fmaiz": require('../../assets/images/fmaiz/i1.webp'),
  "galeana": require('../../assets/images/galeana/i1.webp'),
  "geronimo": require('../../assets/images/geronimo/i1.webp'),
  "granlogia": require('../../assets/images/granlogia/i1.webp'),
  "hiturbide": require('../../assets/images/hiturbide/i1.webp'),
  "hmilitar": require('../../assets/images/hmilitar/i1.webp'),
  "hospmonterrey": require('../../assets/images/hospmonterrey/i1.webp'),
  "hoteferro": require('../../assets/images/hoteferro/i1.webp'),
  "hotelMex": require('../../assets/images/hotelMex/i1.webp'),
  "imprenta": require('../../assets/images/imprenta/i1.webp'),
  "jardoncoss": require('../../assets/images/jardoncoss/i1.webp'),
  "juarezMata": require('../../assets/images/juarezMata/i1.webp'),
  "juarezmatamoros": require('../../assets/images/juarezmatamoros/i1.webp'),
  "londres": require('../../assets/images/londres/i1.webp'),
  "mercadoColon": require('../../assets/images/mercadoColon/i1.webp'),
  "mieryroble": require('../../assets/images/mieryroble/i1.webp'),
  "morelos": require('../../assets/images/morelos/i1.webp'),
  "morelosGaleana": require('../../assets/images/morelosGaleana/i1.webp'),
  "moreloszaragoza": require('../../assets/images/moreloszaragoza/i1.webp'),
  "obispado": require('../../assets/images/obispado/i1.webp'),
  "paletos": require('../../assets/images/paletos/i1.webp'),
  "palMun": require('../../assets/images/palMun/i1.webp'),
  "pdegollado": require('../../assets/images/pdegollado/i1.webp'),
  "pgobierno": require('../../assets/images/pgobierno/i1.webp'),
  "pgonza": require('../../assets/images/pgonza/i1.webp'),
  "prepa3": require('../../assets/images/prepa3/i1.webp'),
  "presaChica": require('../../assets/images/presaChica/i1.webp'),
  "psan": require('../../assets/images/psan/i1.webp'),
  "puente-juarez": require('../../assets/images/puente-juarez/i1.webp'),
  "puenteJ": require('../../assets/images/puenteJ/i1.webp'),
  "purisima": require('../../assets/images/purisima/i1.webp'),
  "pzaragoza": require('../../assets/images/pzaragoza/i1.webp'),
  "reinera": require('../../assets/images/reinera/i1.webp'),
  "rf": require('../../assets/images/rf/i1.webp'),
  "salinasrocha": require('../../assets/images/salinasrocha/i1.webp'),
  "semaforo": require('../../assets/images/semaforo/i1.webp'),
  "tarnava": require('../../assets/images/tarnava/i1.webp'),
  "teatroJuarez": require('../../assets/images/teatroJuarez/i1.webp'),
  "teatroProg": require('../../assets/images/teatroProg/i1.webp'),
  "tmirador": require('../../assets/images/tmirador/i1.webp'),
  "toros": require('../../assets/images/toros/i1.webp'),
  "tSorpresa": require('../../assets/images/tSorpresa/i1.webp'),
  "vidaurri": require('../../assets/images/vidaurri/i1.webp'),
  "villistas": require('../../assets/images/villistas/i1.webp'),
  "vistaBravo": require('../../assets/images/vistaBravo/i1.webp'),
  "vr": require('../../assets/images/vr/i1.webp'),
  "zaramier": require('../../assets/images/zaramier/i1.webp'),
  "zuazua": require('../../assets/images/zuazua/i1.webp'),
  default: require('../../assets/images/icons/main.jpg'),
};

const markerImageCarousels = {
  "alameda": [
    require('../../assets/images/alameda/i1.webp'),
    require('../../assets/images/alameda/i2.webp'),
    require('../../assets/images/alameda/i3.webp'),
    require('../../assets/images/alameda/i4.webp'),
    require('../../assets/images/alameda/i5.webp'),
  ],
  "arco": [
    require('../../assets/images/arco/i1.webp'),
    require('../../assets/images/arco/i2.webp'),
    require('../../assets/images/arco/i3.webp'),
  ],
  "bguadalupe": [
    require('../../assets/images/bguadalupe/i1.webp'),
    require('../../assets/images/bguadalupe/i2.webp'),
    require('../../assets/images/bguadalupe/i3.webp'),
    require('../../assets/images/bguadalupe/i4.webp'),
    require('../../assets/images/bguadalupe/i5.webp'),
  ],
  "botica": [
    require('../../assets/images/botica/i1.webp'),
    require('../../assets/images/botica/i2.webp'),
  ],
  "capLourdes": [
    require('../../assets/images/capLourdes/i1.webp'),
    require('../../assets/images/capLourdes/i2.webp'),
    require('../../assets/images/capLourdes/i3.webp'),
  ],
  "capuchinas": [
    require('../../assets/images/capuchinas/i1.webp'),
    require('../../assets/images/capuchinas/i2.webp'),
    require('../../assets/images/capuchinas/i3.webp'),
  ],
  "casabanos": [
    require('../../assets/images/casabanos/i1.webp'),
    require('../../assets/images/casabanos/i2.webp'),
  ],
  "catedral-mty": [
    require('../../assets/images/catedral-mty/i1.webp'),
    require('../../assets/images/catedral-mty/i2.webp'),
    require('../../assets/images/catedral-mty/i3.webp'),
  ],
  "ccivil": [
    require('../../assets/images/ccivil/i1.webp'),
    require('../../assets/images/ccivil/i2.webp'),
    require('../../assets/images/ccivil/i3.webp'),
    require('../../assets/images/ccivil/i4.webp'),
  ],
  "cine-elizondo": [
    require('../../assets/images/cine-elizondo/i1.webp'),
    require('../../assets/images/cine-elizondo/i2.webp'),
    require('../../assets/images/cine-elizondo/i3.webp'),
  ],
  "ciudadela": [
    require('../../assets/images/ciudadela/i1.webp'),
    require('../../assets/images/ciudadela/i2.webp'),
    require('../../assets/images/ciudadela/i3.webp'),
  ],
  "croble": [
    require('../../assets/images/croble/i1.webp'),
    require('../../assets/images/croble/i2.webp'),
  ],
  "cSA": [
    require('../../assets/images/cSA/i1.webp'),
    require('../../assets/images/cSA/i2.webp'),
    require('../../assets/images/cSA/i3.webp'),
    require('../../assets/images/cSA/i4.webp'),
  ],
  "edamas": [
    require('../../assets/images/edamas/i1.webp'),
    require('../../assets/images/edamas/i2.webp'),
  ],
  "ferro": [
    require('../../assets/images/ferro/i1.webp'),
    require('../../assets/images/ferro/i2.webp'),
  ],
  "galeana": [
    require('../../assets/images/galeana/i1.webp'),
    require('../../assets/images/galeana/i2.webp'),
  ],
  "granlogia": [
    require('../../assets/images/granlogia/i1.webp'),
    require('../../assets/images/granlogia/i2.webp'),
  ],
  "hiturbide": [
    require('../../assets/images/hiturbide/i1.webp'),
    require('../../assets/images/hiturbide/i2.webp'),
    require('../../assets/images/hiturbide/i3.webp'),
    require('../../assets/images/hiturbide/i4.webp'),
  ],
  "mercadoColon": [
    require('../../assets/images/mercadoColon/i1.webp'),
    require('../../assets/images/mercadoColon/i2.webp'),
    require('../../assets/images/mercadoColon/i3.webp'),
    require('../../assets/images/mercadoColon/i4.webp'),
    require('../../assets/images/mercadoColon/i5.webp'),
  ],
  "morelos": [
    require('../../assets/images/morelos/i1.webp'),
    require('../../assets/images/morelos/i2.webp'),
    require('../../assets/images/morelos/i3.webp'),
    require('../../assets/images/morelos/i4.webp'),
    require('../../assets/images/morelos/i5.webp'),
  ],
  "moreloszaragoza": [
    require('../../assets/images/moreloszaragoza/i1.webp'),
    require('../../assets/images/moreloszaragoza/i2.webp'),
    require('../../assets/images/moreloszaragoza/i3.webp'),
    require('../../assets/images/moreloszaragoza/i4.webp'),
  ],
  "obispado": [
    require('../../assets/images/obispado/i1.webp'),
    require('../../assets/images/obispado/i2.webp'),
    require('../../assets/images/obispado/i3.webp'),
  ],
  "palMun": [
    require('../../assets/images/palMun/i1.webp'),
    require('../../assets/images/palMun/i2.webp'),
    require('../../assets/images/palMun/i3.webp'),
    require('../../assets/images/palMun/i4.webp'),
    require('../../assets/images/palMun/i5.webp'),
  ],
  "pdegollado": [
    require('../../assets/images/pdegollado/i1.webp'),
    require('../../assets/images/pdegollado/i2.webp'),
    require('../../assets/images/pdegollado/i3.webp'),
    require('../../assets/images/pdegollado/i4.webp'),
  ],
  "pgobierno": [
    require('../../assets/images/pgobierno/i1.webp'),
    require('../../assets/images/pgobierno/i2.webp'),
    require('../../assets/images/pgobierno/i3.webp'),
    require('../../assets/images/pgobierno/i4.webp'),
    require('../../assets/images/pgobierno/i5.webp'),
    require('../../assets/images/pgobierno/i6.webp'),
    require('../../assets/images/pgobierno/i7.webp'),
  ],
  "prepa3": [
    require('../../assets/images/prepa3/i1.webp'),
    require('../../assets/images/prepa3/i2.webp'),
    require('../../assets/images/prepa3/i3.webp'),
    require('../../assets/images/prepa3/i4.webp'),
  ],
  "psan": [
    require('../../assets/images/psan/i1.webp'),
    require('../../assets/images/psan/i2.webp'),
    require('../../assets/images/psan/i3.webp'),
    require('../../assets/images/psan/i4.webp'),
    require('../../assets/images/psan/i5.webp'),
    require('../../assets/images/psan/i6.webp'),
    require('../../assets/images/psan/i7.webp'),
  ],
  "puente-juarez": [
    require('../../assets/images/puente-juarez/i1.webp'),
    require('../../assets/images/puente-juarez/i2.webp'),
    require('../../assets/images/puente-juarez/i3.webp'),
    require('../../assets/images/puente-juarez/i4.webp'),
  ],
  "purisima": [
    require('../../assets/images/purisima/i1.webp'),
    require('../../assets/images/purisima/i2.webp'),
    require('../../assets/images/purisima/i3.webp'),
    require('../../assets/images/purisima/i4.webp'),
  ],
  "pzaragoza": [
    require('../../assets/images/pzaragoza/i1.webp'),
    require('../../assets/images/pzaragoza/i2.webp'),
    require('../../assets/images/pzaragoza/i3.webp'),
    require('../../assets/images/pzaragoza/i4.webp'),
    require('../../assets/images/pzaragoza/i5.webp'),
    require('../../assets/images/pzaragoza/i6.webp'),
    require('../../assets/images/pzaragoza/i7.webp'),
  ],
  "reinera": [
    require('../../assets/images/reinera/i1.webp'),
    require('../../assets/images/reinera/i2.webp'),
    require('../../assets/images/reinera/i3.webp'),
    require('../../assets/images/reinera/i4.webp'),
  ],
  "teatroJuarez": [
    require('../../assets/images/teatroJuarez/i1.webp'),
    require('../../assets/images/teatroJuarez/i2.webp'),
    require('../../assets/images/teatroJuarez/i3.webp'),
    require('../../assets/images/teatroJuarez/i4.webp'),
    require('../../assets/images/teatroJuarez/i5.webp'),
  ],
  "tSorpresa": [
    require('../../assets/images/tSorpresa/i1.webp'),
    require('../../assets/images/tSorpresa/i2.webp'),
    require('../../assets/images/tSorpresa/i3.webp'),
    require('../../assets/images/tSorpresa/i4.webp'),
  ],
};

export function getMarkerImageSource(markerId) {
  return markerImages[markerId] ?? markerImages.default;
}

export function getMarkerImages(markerId) {
  return markerImageCarousels[markerId] ?? [getMarkerImageSource(markerId)];
}
